UGACT-602 Navigation style adjustments
AutoScout24/showcar-ui pull request #233
Opened 2021-09-10 10:22 UTC by KamilChoroba

* Allow max width for submenu-items
* Break submenu-items in case there is
  not enough space to visualize the full text
* Add css class for smyle icon

2021-09-10 12:36 UTC, ctoutountzidis approved these changes

2021-09-13 11:25 UTC, lakhaNamdhari requested changes
Hey Kamil - I have added few comments.

2021-09-13 11:25 UTC, lakhaNamdhari commented on src/06-components/organisms/navigation-v2/navigation-v2.scss
> +.sc-navigation-v2 button.smyle-header-menu:after {
This block can already be nested under `button.smyle-header-menu {`

2021-09-13 11:25 UTC, lakhaNamdhari commented on src/06-components/organisms/navigation-v2/navigation-v2.scss
> +.sc-navigation-v2 button.smyle-header-menu {
This block can already be nested under `.sc-navigation-v2` at line:6

2021-09-13 11:25 UTC, lakhaNamdhari commented on src/06-components/organisms/navigation-v2/navigation-v2.scss
> +}
Could you please add this block under scope of `..sc-navigation-v2`?  defined (line:6)

2021-09-13 11:25 UTC, lakhaNamdhari commented on src/06-components/organisms/navigation-v2/navigation-v2-mixin.scss
> +        white-space: nowrap;
We should check the impact of these style changes on dealer navigation as it seems to use this mixin.

https://github.com/AutoScout24/as24-dealer-navigation/blob/2dd9c685205d9513b9f786b1f9e635d33756e162/ui/scss/header.scss#L15

you could quickly check with Martin Lechner as they own dealer navigation AFAIK.

2021-09-13 12:02 UTC, KamilChoroba commented on src/06-components/organisms/navigation-v2/navigation-v2-mixin.scss
> +        white-space: nowrap;
Seems to look fine. I've tested the dealer-navigation locally and it looks good. I think they use somehow another prefix `as24dn__nav`.

2021-09-13 12:15 UTC, lakhaNamdhari approved these changes

2021-09-13 12:22 UTC, merged